baseURL = 'https://stu.systems/'
languageCode = 'en-us'
title = 'Stu Rides Bikes (and does other stuff)'
theme = 'ananke'

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "pink"
recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/tuzgai"
share = false
[[params.ananke_socials]]
name = "mastodon"
url = "https://dice.camp/@tuzgai"
rel = "me noopener"
share = false
[[params.ananke_socials]]
name = "bsky"
url = "https://bsky.app/profile/stu.systems"
label = "bsky"
color = "light-blue"
share = false
